"""user edits

Revision ID: 225f73b83838
Revises: 41ef5100aec9
Create Date: 2019-04-04 23:14:39.300411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225f73b83838'
down_revision = '41ef5100aec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('guests_confirmed', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('total_guests', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('update_date_RSVP', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_times')
    op.drop_column('user', 'update_date_RSVP')
    op.drop_column('user', 'total_guests')
    op.drop_column('user', 'guests_confirmed')
    # ### end Alembic commands ###
